<a href="https://colab.research.google.com/github/AndreiAf02/Cholera/blob/main/Cholera_Extension_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pylab inline
%config InlineBackend.figure_format = 'retina'
from ipywidgets import interact
import scipy.stats as stats
import pandas as pd
import pymc as pm
import seaborn as sns

Populating the interactive namespace from numpy and matplotlib

In [4]:
path_to_data = 'https://raw.githubusercontent.com/AndreiAf02/Cholera/main/'
data_all = pd.read_csv(path_to_data + "Chol_Africa_Cumul.csv", sep=",", header=0)
data_all

,Date,Day,Burundi,Comoros,Ethiopia,Kenya,Malawi,Mozambique,Somalia,Sudan,Zambia,Zimbabwe
0,2023-01-06,1,12.0,NaN,NaN,347.0,3055.0,NaN,NaN,NaN,NaN,NaN
1,2023-01-13,8,63.0,NaN,NaN,NaN,7131.0,1014.0,NaN,NaN,NaN,NaN
2,2023-01-21,16,114.0,NaN,NaN,980.0,12046.0,1776.0,NaN,NaN,NaN,NaN
3,2023-01-27,22,NaN,NaN,NaN,1336.0,15746.0,2256.0,703.0,NaN,11.0,NaN
4,2023-02-03,29,NaN,NaN,NaN,1541.0,20172.0,2602.0,NaN,NaN,27.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
61,2024-04-14,465,1317.0,787.0,34662.0,NaN,42594.0,43803.0,NaN,NaN,21707.0,28840.0
62,2024-04-20,471,1322.0,1769.0,NaN,NaN,42607.0,44038.0,21964.0,NaN,21884.0,29429.0
63,2024-04-28,479,1331.0,2498.0,37302.0,NaN,42617.0,44238.0,22699.0,10295.0,22052.0,30179.0
64,2024-05-05,486,1344.0,3864.0,38071.0,NaN,42619.0,44352.0,23410.0,NaN,22107.0,30572.0
65,2024-05-12,493,1345.0,4976.0,39729.0,8804.0,NaN,44480.0,24104.0,NaN,22161.0,30994.0